### ISSUE TITLE
Wallet Connect is not working.

### ISSUE THREAD

**Issue by frundik** [ethereum-boilerplate/ethereum-boilerplate#119]
In this example (https://ethereum-boilerplate.github.io/ethereum-boilerplate/quickstart), I cannot connect, for example, with Trust Wallet

I scan the QR on my phone, do all the necessary confirmations, but there is no authorization on the site.

I have the same problem on my local server.

**Comment by mimiqkz** [comment]
I can confirm that this is not working at all

**Comment by mykcryptodev** [comment]
I too have this issue.

**Comment by mykcryptodev** [comment]
@frundik @Y0moo Any news on this?

**Comment by Y0moo** [comment]
This issue will be fixed after we release official 2.0 version of the Ethereum Boilerplate

**Comment by SpencerCooley** [comment]
Any updates on this? When I try to connect it just opens metamask on android and then does nothing.

**Comment by Y0moo** [comment]
Closing since we released V2

**Comment by tatumalgorand** [comment]
Hi,
Firstly thank you very much for your hard work on the boilerplate. 
I have an issue with the Connect Wallet button on mobile devices and wonder f you had any advice to help me get it working.
When I click Connect Wallet I receive a response saying connector not found. 
I have the boilerplate installed on ubuntu 20.04 and is running great on Desktop. Everything works as expected and I receive no errors.
However when pressing the Connect Wallet button on a mobile device or tablet, I receive the error Oops something went wrong ... Connector not found.

I presume this is due to the Dapp looking for the Desktop wallet extension rather than either a deeplink or connecting link such as wc:// ( for wallet connect to link to the mobile website ).

Im not an experienced Java coder by any means so if anyone could point me in the right direction I would greatly appreciate it.

Thanks in advance
Danny
