### ISSUE TITLE
[UI] Layout

### ISSUE THREAD

**Issue by Y0moo** [ethereum-boilerplate/ethereum-boilerplate#165]

**Comment by jeffscottward** [comment]
Hey all,

I know this is of course your code repo demo and you can make all the decisions you want but just a thought for the V2 revamp:

I've been perfecting a UI boilerplate on top of Next.JS for quite some time now, and I've gotten to the point of being *extremely terse and opt-in flexible* that I thought it was worth mentioning as a guide for inspiration.

Global state 1 hook
ThemeUI for constraint based, in-line flexibility and speed
RainbowKit provider (I know this is only ETH 🤷🏻‍♂️)
React Query
Animate.css (just add 'animate [anim]' in a class)
Pre-built button permutations + style flexibility
Etc etc

https://github.com/jeffscottward/dapp-base

I bring this up because I often feel that whole complete UIkits (i.e. Web3UIKit) are something you often have to fight against, or are specific to a brand, or something you'll have to rip out and replace, or avoid and will cherry pick the utility out of the boilerplate to get around it. Also web3uikit seems under active development as is but maybe it's more mature than I've looked into, just giving the senior dev gif reaction.

What I'm hoping to see is the core utility stuff as cleanly separated from UI assumptions as possible at the least if you want to go with the web3uikit approach.

Anyways, I would say try cloning my project and see how fast you can make something.

(It's actually occurring to me I don't have react forms solution in there yet, will need to add. https://www.kindacode.com/article/top-react-form-validation-libraries/ )

Anyways hope my thoughts are welcome

Jeff

**Comment by Y0moo** [comment]
Closing since we released V2
