### ISSUE TITLE
Make a Hardhat version please

### ISSUE THREAD

**Issue by adriandelgg** [ethereum-boilerplate/ethereum-boilerplate#21]
This is a suggestion, not an issue.

I believe it should be made with Hardhat instead of Truffle due to the industry moving more and more towards Hardhat.

That's all. Great job! :)

**Comment by locothedev** [comment]
Thanks for your suggestion.

Please use our forum next time for this reason.

https://forum.moralis.io/t/ethereum-boilerplate-questions/3951/49

**Comment by Y0moo** [comment]
Hi @adriandelgg ! Thank you for your feedback!

We selected Truffle because it can save localchain data. So when you stop your devchain and run it again you will not loose your previous data. This is important because it makes easier syncing local devchain with Moralis Database.

Does the HardHat have such functionality?

**Comment by adriandelgg** [comment]
> Hi @adriandelgg ! Thank you for your feedback!
> 
> We selected Truffle because it can save localchain data. So when you stop your devchain and run it again you will not loose your previous data. This is important because it makes easier syncing local devchain with Moralis Database.
> 
> Does the HardHat have such functionality?

That's a good point. I'm not exactly sure, but I do know that Hardhat has a plugin to be able to use Ganache. It _may_ allow to save the state, not entirely sure.

https://hardhat.org/plugins/nomiclabs-hardhat-ganache.html
